### PR TITLE
fixes for building on SunOS

### PR DESCRIPTION
**Pull request by DBarney**

### CODE REVIEW

**Comment by creationix** [comment]
+1

**Comment by rphillips** [comment]
this patch may fix the 32bit as well.

**Comment by creationix** [comment]
what do we need in the conditional to catch it for 32-bit?  I think this is what's breaking static build in armv6l and armv7l.

**Comment by DBarney** [comment]
looks like this could be how to check for 64/32 bit in CMake

```if( CMAKE_SIZEOF_VOID_P EQUAL 8 )```
http://stackoverflow.com/questions/17317350/compiling-32-and-64-bit

**Comment by rphillips** [comment]
perhaps we should unconditionally set this option on line https://github.com/DBarney/openssl/blob/master/openssl.cmake#L832

**Comment by DBarney** [comment]
So I put in in before the system checks because it is possible that a system is 32 bit and would need this flag.

**Pull request merged**
